import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';
import type { Bill, BillSummaryData, CachedBillSummary } from '@/types';
import { getAdminDb } from '@/lib/firebase-admin';
import { checkRateLimit, getClientIp, isSameOrigin } from '@/lib/rateLimit';
import { summaryDocId, SUMMARY_PROMPT_VERSION } from '@/lib/summaryCacheKey';

// ── Singleton AI client (module-level = one instance per server process) ──────

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY ?? '');

const model = genAI.getGenerativeModel({
  model: 'gemini-2.5-flash',
  generationConfig: {
    temperature: 0.3,
    maxOutputTokens: 8192,
    responseMimeType: 'application/json',
  },
});

// ── In-memory cache (same logic as original GeminiService) ────────────────────

interface CacheEntry {
  data: BillSummaryData;
  timestamp: number;
}

const CACHE_DURATION = 24 * 60 * 60 * 1000; // 24 hours
const REQUEST_DELAY = 4000;                  // 4 seconds between Gemini requests
const RATE_LIMIT_MAX_REQUESTS = 10; // per window, per IP
const RATE_LIMIT_WINDOW_MS = 60 * 1000; // 1 minute
const MAX_TITLE_LENGTH = 300;
const MAX_ABSTRACT_LENGTH = 4000;

/** A resolved summary plus where it came from — a Firestore hit must not be written back. */
interface ResolvedSummary {
  data: BillSummaryData;
  fromCache: boolean;
}

const summaryCache = new Map<string, CacheEntry>();
const pendingRequests = new Map<string, Promise<ResolvedSummary>>();
let lastRequestTime = 0;

const FALLBACK: BillSummaryData = {
  gist: 'Summary unavailable at this time.',
  whoItAffects: 'General public',
  walletImpact: 'No direct cost impact.',
  controversy: { for: [], against: [] },
};

/** A Gemini failure returns FALLBACK; it must never be cached in L1 or L2. */
const isFallback = (d: BillSummaryData) => d.gist === FALLBACK.gist;

function isCacheValid(entry: CacheEntry): boolean {
  return Date.now() - entry.timestamp < CACHE_DURATION;
}

/**
 * LIMITATION: `lastRequestTime` is a module global, so this only spaces Gemini
 * calls within a single server process. On Vercel, concurrent lambda instances
 * each have their own copy and do not space calls against each other. The
 * per-IP limiter in the handler is the real protection here.
 */
async function enforceRateLimit(): Promise<void> {
  const timeSince = Date.now() - lastRequestTime;
  if (timeSince < REQUEST_DELAY) {
    await new Promise(resolve => setTimeout(resolve, REQUEST_DELAY - timeSince));
  }
  lastRequestTime = Date.now();
}

function parseResponse(text: string): BillSummaryData {
  try {
    return JSON.parse(text) as BillSummaryData;
  } catch {
    console.error('[/api/summarize] JSON parse failed:', text.slice(0, 500));
    return FALLBACK;
  }
}

async function generateForBill(bill: Bill): Promise<BillSummaryData> {
  await enforceRateLimit();

  let context = `Bill Title: "${bill.title}"`;
  if (bill.abstracts && bill.abstracts.length > 0 && bill.abstracts[0].abstract) {
    context += `\nOfficial Abstract: "${bill.abstracts[0].abstract}"`;
  }
  if (bill.subject && bill.subject.length > 0) {
    context += `\nSubjects: ${bill.subject.join(', ')}`;
  }
  if (bill.latest_action_description) {
    context += `\nLatest Action: ${bill.latest_action_description}`;
  }

  const prompt = `You are a legislative analyst. Respond ONLY with a valid JSON object — no markdown, no explanation, no extra text.

Use this exact schema:
{
  "gist": "1-3 sentence plain-English summary of what this bill does",
  "whoItAffects": "The primary group affected (e.g. homeowners, teachers, small businesses)",
  "walletImpact": "Direct financial effect — costs, taxes, fines, or savings. If none, say 'No direct cost impact.'",
  "controversy": {
    "for": ["1-2 short bullet points supporting the bill"],
    "against": ["1-2 short bullet points opposing the bill"]
  }
}

Bill information:
${context}`;

  try {
    const result = await model.generateContent(prompt);
    return parseResponse(result.response.text().trim());
  } catch (error) {
    console.error('[/api/summarize] Gemini error:', error);
    return FALLBACK;
  }
}

/** L2 read. Returns null on any miss, stale prompt version, or read failure. */
async function readCachedSummary(billId: string): Promise<BillSummaryData | null> {
  try {
    const snap = await getAdminDb().collection('bill_summaries').doc(summaryDocId(billId)).get();
    if (!snap.exists) return null;
    const data = snap.data() as CachedBillSummary | undefined;
    if (!data?.gist) return null;
    // A doc generated by an older prompt is treated as a miss so it gets regenerated once.
    if ((data._meta?.promptVersion ?? 0) < SUMMARY_PROMPT_VERSION) return null;
    return data;
  } catch (err) {
    console.error('[/api/summarize] Firestore read failed:', err);
    return null; // fail open — a read failure must not block the user, only cost a generation
  }
}

/**
 * The Firestore read lives inside this function (and therefore inside the
 * deduplicated promise) on purpose: if it ran before the dedupe, two concurrent
 * cold requests would both miss L1 and both pay for a Gemini generation.
 */
async function resolveForBill(bill: Bill): Promise<ResolvedSummary> {
  const cached = await readCachedSummary(bill.id);
  if (cached) return { data: cached, fromCache: true };
  return { data: await generateForBill(bill), fromCache: false };
}

// ── Route handler ─────────────────────────────────────────────────────────────

export async function POST(request: NextRequest) {
  if (!isSameOrigin(request)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  const ip = getClientIp(request);
  const { allowed } = checkRateLimit(`summarize:${ip}`, RATE_LIMIT_MAX_REQUESTS, RATE_LIMIT_WINDOW_MS);
  if (!allowed) {
    return NextResponse.json({ error: 'Too many requests. Please slow down.' }, { status: 429 });
  }

  let bill: Bill;

  try {
    const body = await request.json() as { bill: Bill };
    bill = body.bill;
    if (!bill?.title || typeof bill.title !== 'string') throw new Error('Missing bill.title');
    if (!bill?.id || typeof bill.id !== 'string') throw new Error('Missing bill.id');
    // Cap (rather than reject) overlong input so legitimate long official titles
    // still summarize, while bounding the tokens sent to Gemini.
    if (bill.title.length > MAX_TITLE_LENGTH) {
      bill.title = bill.title.slice(0, MAX_TITLE_LENGTH);
    }
    if (bill.abstracts?.[0]?.abstract && bill.abstracts[0].abstract.length > MAX_ABSTRACT_LENGTH) {
      bill.abstracts[0].abstract = bill.abstracts[0].abstract.slice(0, MAX_ABSTRACT_LENGTH);
    }
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  // Keyed on the bill id, never the title: two bills sharing a title prefix are
  // still two different bills. (The title truncation above only bounds tokens.)
  const cacheKey = summaryDocId(bill.id);

  // L1: in-memory server cache
  const cached = summaryCache.get(cacheKey);
  if (cached && isCacheValid(cached)) {
    return NextResponse.json(cached.data);
  }

  // Deduplicate concurrent requests for the same bill
  if (pendingRequests.has(cacheKey)) {
    const { data } = await pendingRequests.get(cacheKey)!;
    return NextResponse.json(data);
  }

  const requestPromise = resolveForBill(bill);
  pendingRequests.set(cacheKey, requestPromise);

  try {
    const { data, fromCache } = await requestPromise;

    // Never persist the fallback (it would poison this bill permanently), and
    // never rewrite a doc that came straight out of Firestore.
    if (!isFallback(data)) {
      summaryCache.set(cacheKey, { data, timestamp: Date.now() });

      if (!fromCache) {
        // L2: write to the shared Firestore cache server-side (clients can no longer write this directly)
        try {
          await getAdminDb().collection('bill_summaries').doc(summaryDocId(bill.id)).set({
            ...data,
            _meta: {
              generatedAt: new Date().toISOString(),
              model: 'gemini-2.5-flash',
              promptVersion: SUMMARY_PROMPT_VERSION,
            },
          });
        } catch (err) {
          console.error('[/api/summarize] Failed to write Firestore cache:', err);
          // Non-fatal: the client still gets the summary even if the shared cache write fails
        }
      }
    }

    return NextResponse.json(data);
  } finally {
    pendingRequests.delete(cacheKey);
  }
}
